# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_waywiserrr_wrappers", use_symbols = TRUE, package_name = "waywiserrr")

#' @docType package
#' @usage NULL
#' @useDynLib waywiserrr, .registration = TRUE
NULL

d_bar <- function(a) .Call(wrap__d_bar, a)

gmfr_rust <- function(truth, estimate, corsign) .Call(wrap__gmfr_rust, truth, estimate, corsign)

ssd_rust <- function(truth, estimate) .Call(wrap__ssd_rust, truth, estimate)

spod_rust <- function(truth, estimate) .Call(wrap__spod_rust, truth, estimate)

spdu_rust <- function(truth, estimate, corsign) .Call(wrap__spdu_rust, truth, estimate, corsign)

spds_rust <- function(truth, estimate, corsign) .Call(wrap__spds_rust, truth, estimate, corsign)

